package dev.folio.tools.icongen

/** A Lucide icon ready for code generation: file name without `.svg` and its converted paths. */
internal data class LucideIcon(
    val lucideName: String,
    val paths: List<IconPath>,
)

/**
 * Writes `FolioIcons.kt`: one lazily built ImageVector per icon, calling the hand-written helpers in
 * core:designsystem (`lucideIcon`, `stroke`, `filled`). Output is ktlint-clean so `spotlessApply` leaves it unchanged.
 */
internal object KotlinEmitter {
    /** Path data longer than this is split into several string arguments (joined with a space at runtime). */
    const val CHUNK_CHARS = 100

    fun emit(
        icons: List<LucideIcon>,
        lucideVersion: String,
    ): String =
        buildString {
            appendLine("// Generated by tools:icongen from Lucide $lucideVersion (ISC license, tools/icongen/src/main/resources/lucide).")
            appendLine("// Do not edit. Add the SVG to that folder, then run ./gradlew :tools:icongen:run.")
            appendLine("// One property per icon: the object is large by design.")
            appendLine("@file:Suppress(\"LargeClass\")")
            appendLine()
            appendLine("package dev.folio.core.designsystem.icon")
            appendLine()
            appendLine("import androidx.compose.ui.graphics.vector.ImageVector")
            appendLine()
            appendLine("/** Lucide icons as ImageVectors, stroke 2 with round caps and joins (11-design-system.md#icons). */")
            appendLine("object FolioIcons {")
            val sorted = icons.sortedBy { it.lucideName }
            appendLine("    /** Every icon with its Lucide name (component catalog). */")
            appendLine("    internal val all: List<Pair<String, ImageVector>>")
            appendLine("        get() =")
            appendLine("            listOf(")
            sorted.forEach { appendLine("                \"${it.lucideName}\" to ${propertyName(it.lucideName)},") }
            appendLine("            )")
            sorted.forEach { icon ->
                appendLine()
                val name = propertyName(icon.lucideName)
                appendLine("    /** Lucide `${icon.lucideName}`. */")
                appendLine("    val $name: ImageVector by lazy {")
                appendLine("        lucideIcon(")
                appendLine("            \"$name\",")
                icon.paths.forEach { appendPath(it) }
                appendLine("        )")
                appendLine("    }")
            }
            appendLine("}")
        }

    /** `arrow-down-wide-narrow` -> `ArrowDownWideNarrow`, `columns-2` -> `Columns2`. */
    fun propertyName(lucideName: String): String =
        lucideName.split('-').joinToString("") { part -> part.replaceFirstChar { it.uppercaseChar() } }

    /** Splits at spaces or before command letters so every chunk is at most [CHUNK_CHARS] long. */
    fun chunk(pathData: String): List<String> {
        val chunks = mutableListOf<String>()
        var rest = pathData
        while (rest.length > CHUNK_CHARS) {
            val window = rest.substring(0, CHUNK_CHARS + 1)
            val cut = window.indexOfLast { it == ' ' || it.isLetter() }.takeIf { it > 0 } ?: CHUNK_CHARS
            chunks += rest.substring(0, cut).trimEnd()
            rest = rest.substring(cut).trimStart()
        }
        chunks += rest
        return chunks
    }

    private fun StringBuilder.appendPath(path: IconPath) {
        val function = if (path.filled) "filled" else "stroke"
        val chunks = chunk(path.pathData)
        if (chunks.size == 1) {
            appendLine("            $function(\"${chunks[0]}\"),")
        } else {
            appendLine("            $function(")
            chunks.forEach { appendLine("                \"$it\",") }
            appendLine("            ),")
        }
    }
}
