// Generated by tools:icongen from Lucide 1.49.0 (ISC license, tools/icongen/src/main/resources/lucide).
// Do not edit. Add the SVG to that folder, then run ./gradlew :tools:icongen:run.
// One property per icon: the object is large by design.
@file:Suppress("LargeClass")

package dev.folio.core.designsystem.icon

import androidx.compose.ui.graphics.vector.ImageVector

/** Lucide icons as ImageVectors, stroke 1.75 with round caps and joins (11-design-system.md#icons). */
object FolioIcons {
    /** Every icon with its Lucide name (component catalog). */
    internal val all: List<Pair<String, ImageVector>>
        get() =
            listOf(
                "arrow-down-wide-narrow" to ArrowDownWideNarrow,
                "bold" to Bold,
                "camera" to Camera,
                "check" to Check,
                "chevron-down" to ChevronDown,
                "chevron-left" to ChevronLeft,
                "chevron-right" to ChevronRight,
                "circle" to Circle,
                "circle-check" to CircleCheck,
                "circle-plus" to CirclePlus,
                "code" to Code,
                "columns-2" to Columns2,
                "crop" to Crop,
                "download" to Download,
                "ellipsis" to Ellipsis,
                "eraser" to Eraser,
                "file-plus" to FilePlus,
                "file-text" to FileText,
                "file-up" to FileUp,
                "folder" to Folder,
                "folder-plus" to FolderPlus,
                "grip-vertical" to GripVertical,
                "heading-1" to Heading1,
                "heading-2" to Heading2,
                "heading-3" to Heading3,
                "hexagon" to Hexagon,
                "highlighter" to Highlighter,
                "house" to House,
                "image" to Image,
                "infinity" to Infinity,
                "italic" to Italic,
                "keyboard" to Keyboard,
                "lasso" to Lasso,
                "layout-grid" to LayoutGrid,
                "link" to Link,
                "list" to List,
                "list-checks" to ListChecks,
                "list-ordered" to ListOrdered,
                "maximize-2" to Maximize2,
                "menu" to Menu,
                "minus" to Minus,
                "move-up-right" to MoveUpRight,
                "panel-left" to PanelLeft,
                "paperclip" to Paperclip,
                "pen" to Pen,
                "pen-line" to PenLine,
                "pencil" to Pencil,
                "plus" to Plus,
                "quote" to Quote,
                "redo-2" to Redo2,
                "rotate-ccw" to RotateCcw,
                "ruler" to Ruler,
                "search" to Search,
                "settings" to Settings,
                "shapes" to Shapes,
                "share-2" to Share2,
                "sigma" to Sigma,
                "sliders-horizontal" to SlidersHorizontal,
                "square" to Square,
                "star" to Star,
                "sticky-note" to StickyNote,
                "strikethrough" to Strikethrough,
                "table" to Table,
                "tag" to Tag,
                "trash" to Trash,
                "triangle" to Triangle,
                "type" to Type,
                "undo-2" to Undo2,
                "x" to X,
            )

    /** Lucide `arrow-down-wide-narrow`. */
    val ArrowDownWideNarrow: ImageVector by lazy {
        lucideIcon(
            "ArrowDownWideNarrow",
            stroke("m3 16 4 4 4-4"),
            stroke("M7 20V4"),
            stroke("M11 4h10"),
            stroke("M11 8h7"),
            stroke("M11 12h4"),
        )
    }

    /** Lucide `bold`. */
    val Bold: ImageVector by lazy {
        lucideIcon(
            "Bold",
            stroke("M6 12h9a4 4 0 0 1 0 8H7a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h7a4 4 0 0 1 0 8"),
        )
    }

    /** Lucide `camera`. */
    val Camera: ImageVector by lazy {
        lucideIcon(
            "Camera",
            stroke(
                "M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0",
                "1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z",
            ),
            stroke("M9 13A3 3 0 1 0 15 13A3 3 0 1 0 9 13Z"),
        )
    }

    /** Lucide `check`. */
    val Check: ImageVector by lazy {
        lucideIcon(
            "Check",
            stroke("M20 6 9 17l-5-5"),
        )
    }

    /** Lucide `chevron-down`. */
    val ChevronDown: ImageVector by lazy {
        lucideIcon(
            "ChevronDown",
            stroke("m6 9 6 6 6-6"),
        )
    }

    /** Lucide `chevron-left`. */
    val ChevronLeft: ImageVector by lazy {
        lucideIcon(
            "ChevronLeft",
            stroke("m15 18-6-6 6-6"),
        )
    }

    /** Lucide `chevron-right`. */
    val ChevronRight: ImageVector by lazy {
        lucideIcon(
            "ChevronRight",
            stroke("m9 18 6-6-6-6"),
        )
    }

    /** Lucide `circle`. */
    val Circle: ImageVector by lazy {
        lucideIcon(
            "Circle",
            stroke("M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z"),
        )
    }

    /** Lucide `circle-check`. */
    val CircleCheck: ImageVector by lazy {
        lucideIcon(
            "CircleCheck",
            stroke("M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z"),
            stroke("m16 9-5.5 5.5L8 12"),
        )
    }

    /** Lucide `circle-plus`. */
    val CirclePlus: ImageVector by lazy {
        lucideIcon(
            "CirclePlus",
            stroke("M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12Z"),
            stroke("M8 12h8"),
            stroke("M12 8v8"),
        )
    }

    /** Lucide `code`. */
    val Code: ImageVector by lazy {
        lucideIcon(
            "Code",
            stroke("m16 18 6-6-6-6"),
            stroke("m8 6-6 6 6 6"),
        )
    }

    /** Lucide `columns-2`. */
    val Columns2: ImageVector by lazy {
        lucideIcon(
            "Columns2",
            stroke("M5 3H19A2 2 0 0 1 21 5V19A2 2 0 0 1 19 21H5A2 2 0 0 1 3 19V5A2 2 0 0 1 5 3Z"),
            stroke("M12 3v18"),
        )
    }

    /** Lucide `crop`. */
    val Crop: ImageVector by lazy {
        lucideIcon(
            "Crop",
            stroke("M6 2v14a2 2 0 0 0 2 2h14"),
            stroke("M18 22V8a2 2 0 0 0-2-2H2"),
        )
    }

    /** Lucide `download`. */
    val Download: ImageVector by lazy {
        lucideIcon(
            "Download",
            stroke("M12 15V3"),
            stroke("M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"),
            stroke("m7 10 5 5 5-5"),
        )
    }

    /** Lucide `ellipsis`. */
    val Ellipsis: ImageVector by lazy {
        lucideIcon(
            "Ellipsis",
            stroke("M11 12A1 1 0 1 0 13 12A1 1 0 1 0 11 12Z"),
            stroke("M18 12A1 1 0 1 0 20 12A1 1 0 1 0 18 12Z"),
            stroke("M4 12A1 1 0 1 0 6 12A1 1 0 1 0 4 12Z"),
        )
    }

    /** Lucide `eraser`. */
    val Eraser: ImageVector by lazy {
        lucideIcon(
            "Eraser",
            stroke(
                "M21 21H8a2 2 0 0 1-1.42-.587l-3.994-3.999a2 2 0 0 1 0-2.828l10-10a2 2 0 0 1 2.829 0l5.999 6a2 2 0 0",
                "1 0 2.828L12.834 21",
            ),
            stroke("m5.082 11.09 8.828 8.828"),
        )
    }

    /** Lucide `file-plus`. */
    val FilePlus: ImageVector by lazy {
        lucideIcon(
            "FilePlus",
            stroke(
                "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2",
                "0 0 1-2 2z",
            ),
            stroke("M14 2v5a1 1 0 0 0 1 1h5"),
            stroke("M9 15h6"),
            stroke("M12 18v-6"),
        )
    }

    /** Lucide `file-text`. */
    val FileText: ImageVector by lazy {
        lucideIcon(
            "FileText",
            stroke(
                "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2",
                "0 0 1-2 2z",
            ),
            stroke("M14 2v5a1 1 0 0 0 1 1h5"),
            stroke("M10 9H8"),
            stroke("M16 13H8"),
            stroke("M16 17H8"),
        )
    }

    /** Lucide `file-up`. */
    val FileUp: ImageVector by lazy {
        lucideIcon(
            "FileUp",
            stroke(
                "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2",
                "0 0 1-2 2z",
            ),
            stroke("M14 2v5a1 1 0 0 0 1 1h5"),
            stroke("M12 12v6"),
            stroke("m15 15-3-3-3 3"),
        )
    }

    /** Lucide `folder`. */
    val Folder: ImageVector by lazy {
        lucideIcon(
            "Folder",
            stroke(
                "M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2",
                "v13a2 2 0 0 0 2 2Z",
            ),
        )
    }

    /** Lucide `folder-plus`. */
    val FolderPlus: ImageVector by lazy {
        lucideIcon(
            "FolderPlus",
            stroke("M12 10v6"),
            stroke("M9 13h6"),
            stroke(
                "M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2",
                "v13a2 2 0 0 0 2 2Z",
            ),
        )
    }

    /** Lucide `grip-vertical`. */
    val GripVertical: ImageVector by lazy {
        lucideIcon(
            "GripVertical",
            stroke("M8 12A1 1 0 1 0 10 12A1 1 0 1 0 8 12Z"),
            stroke("M8 5A1 1 0 1 0 10 5A1 1 0 1 0 8 5Z"),
            stroke("M8 19A1 1 0 1 0 10 19A1 1 0 1 0 8 19Z"),
            stroke("M14 12A1 1 0 1 0 16 12A1 1 0 1 0 14 12Z"),
            stroke("M14 5A1 1 0 1 0 16 5A1 1 0 1 0 14 5Z"),
            stroke("M14 19A1 1 0 1 0 16 19A1 1 0 1 0 14 19Z"),
        )
    }

    /** Lucide `heading-1`. */
    val Heading1: ImageVector by lazy {
        lucideIcon(
            "Heading1",
            stroke("M4 12h8"),
            stroke("M4 18V6"),
            stroke("M12 18V6"),
            stroke("m17 12 3-2v8"),
        )
    }

    /** Lucide `heading-2`. */
    val Heading2: ImageVector by lazy {
        lucideIcon(
            "Heading2",
            stroke("M4 12h8"),
            stroke("M4 18V6"),
            stroke("M12 18V6"),
            stroke("M21 18h-4c0-4 4-3 4-6 0-1.5-2-2.5-4-1"),
        )
    }

    /** Lucide `heading-3`. */
    val Heading3: ImageVector by lazy {
        lucideIcon(
            "Heading3",
            stroke("M4 12h8"),
            stroke("M4 18V6"),
            stroke("M12 18V6"),
            stroke("M17.5 10.5c1.7-1 3.5 0 3.5 1.5a2 2 0 0 1-2 2"),
            stroke("M17 17.5c2 1.5 4 .3 4-1.5a2 2 0 0 0-2-2"),
        )
    }

    /** Lucide `hexagon`. */
    val Hexagon: ImageVector by lazy {
        lucideIcon(
            "Hexagon",
            stroke(
                "M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0",
                "l7-4A2 2 0 0 0 21 16z",
            ),
        )
    }

    /** Lucide `highlighter`. */
    val Highlighter: ImageVector by lazy {
        lucideIcon(
            "Highlighter",
            stroke("m9 11-6 6v3h9l3-3"),
            stroke("m22 12-4.6 4.6a2 2 0 0 1-2.8 0l-5.2-5.2a2 2 0 0 1 0-2.8L14 4"),
        )
    }

    /** Lucide `house`. */
    val House: ImageVector by lazy {
        lucideIcon(
            "House",
            stroke("M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"),
            stroke(
                "M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2",
                "z",
            ),
        )
    }

    /** Lucide `image`. */
    val Image: ImageVector by lazy {
        lucideIcon(
            "Image",
            stroke("M5 3H19A2 2 0 0 1 21 5V19A2 2 0 0 1 19 21H5A2 2 0 0 1 3 19V5A2 2 0 0 1 5 3Z"),
            stroke("M7 9A2 2 0 1 0 11 9A2 2 0 1 0 7 9Z"),
            stroke("m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"),
        )
    }

    /** Lucide `infinity`. */
    val Infinity: ImageVector by lazy {
        lucideIcon(
            "Infinity",
            stroke("M6 16c5 0 7-8 12-8a4 4 0 0 1 0 8c-5 0-7-8-12-8a4 4 0 1 0 0 8"),
        )
    }

    /** Lucide `italic`. */
    val Italic: ImageVector by lazy {
        lucideIcon(
            "Italic",
            stroke("M19 4L10 4"),
            stroke("M14 20L5 20"),
            stroke("M15 4L9 20"),
        )
    }

    /** Lucide `keyboard`. */
    val Keyboard: ImageVector by lazy {
        lucideIcon(
            "Keyboard",
            stroke("M10 8h.01"),
            stroke("M12 12h.01"),
            stroke("M14 8h.01"),
            stroke("M16 12h.01"),
            stroke("M18 8h.01"),
            stroke("M6 8h.01"),
            stroke("M7 16h10"),
            stroke("M8 12h.01"),
            stroke("M4 4H20A2 2 0 0 1 22 6V18A2 2 0 0 1 20 20H4A2 2 0 0 1 2 18V6A2 2 0 0 1 4 4Z"),
        )
    }

    /** Lucide `lasso`. */
    val Lasso: ImageVector by lazy {
        lucideIcon(
            "Lasso",
            stroke("M3.704 14.467a10 8 0 1 1 3.115 2.375"),
            stroke("M7 22a5 5 0 0 1-2-3.994"),
            stroke("M3 16A2 2 0 1 0 7 16A2 2 0 1 0 3 16Z"),
        )
    }

    /** Lucide `layout-grid`. */
    val LayoutGrid: ImageVector by lazy {
        lucideIcon(
            "LayoutGrid",
            stroke("M4 3H9A1 1 0 0 1 10 4V9A1 1 0 0 1 9 10H4A1 1 0 0 1 3 9V4A1 1 0 0 1 4 3Z"),
            stroke("M15 3H20A1 1 0 0 1 21 4V9A1 1 0 0 1 20 10H15A1 1 0 0 1 14 9V4A1 1 0 0 1 15 3Z"),
            stroke("M15 14H20A1 1 0 0 1 21 15V20A1 1 0 0 1 20 21H15A1 1 0 0 1 14 20V15A1 1 0 0 1 15 14Z"),
            stroke("M4 14H9A1 1 0 0 1 10 15V20A1 1 0 0 1 9 21H4A1 1 0 0 1 3 20V15A1 1 0 0 1 4 14Z"),
        )
    }

    /** Lucide `link`. */
    val Link: ImageVector by lazy {
        lucideIcon(
            "Link",
            stroke("M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"),
            stroke("M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"),
        )
    }

    /** Lucide `list`. */
    val List: ImageVector by lazy {
        lucideIcon(
            "List",
            stroke("M3 5h.01"),
            stroke("M3 12h.01"),
            stroke("M3 19h.01"),
            stroke("M8 5h13"),
            stroke("M8 12h13"),
            stroke("M8 19h13"),
        )
    }

    /** Lucide `list-checks`. */
    val ListChecks: ImageVector by lazy {
        lucideIcon(
            "ListChecks",
            stroke("M13 5h8"),
            stroke("M13 12h8"),
            stroke("M13 19h8"),
            stroke("m3 17 2 2 4-4"),
            stroke("m3 7 2 2 4-4"),
        )
    }

    /** Lucide `list-ordered`. */
    val ListOrdered: ImageVector by lazy {
        lucideIcon(
            "ListOrdered",
            stroke("M11 5h10"),
            stroke("M11 12h10"),
            stroke("M11 19h10"),
            stroke("M4 4h1v5"),
            stroke("M4 9h2"),
            stroke("M6.5 20H3.4c0-1 2.6-1.925 2.6-3.5a1.5 1.5 0 0 0-2.6-1.02"),
        )
    }

    /** Lucide `maximize-2`. */
    val Maximize2: ImageVector by lazy {
        lucideIcon(
            "Maximize2",
            stroke("M15 3h6v6"),
            stroke("m21 3-7 7"),
            stroke("m3 21 7-7"),
            stroke("M9 21H3v-6"),
        )
    }

    /** Lucide `menu`. */
    val Menu: ImageVector by lazy {
        lucideIcon(
            "Menu",
            stroke("M4 5h16"),
            stroke("M4 12h16"),
            stroke("M4 19h16"),
        )
    }

    /** Lucide `minus`. */
    val Minus: ImageVector by lazy {
        lucideIcon(
            "Minus",
            stroke("M5 12h14"),
        )
    }

    /** Lucide `move-up-right`. */
    val MoveUpRight: ImageVector by lazy {
        lucideIcon(
            "MoveUpRight",
            stroke("M13 5H19V11"),
            stroke("M19 5L5 19"),
        )
    }

    /** Lucide `panel-left`. */
    val PanelLeft: ImageVector by lazy {
        lucideIcon(
            "PanelLeft",
            stroke("M5 3H19A2 2 0 0 1 21 5V19A2 2 0 0 1 19 21H5A2 2 0 0 1 3 19V5A2 2 0 0 1 5 3Z"),
            stroke("M9 3v18"),
        )
    }

    /** Lucide `paperclip`. */
    val Paperclip: ImageVector by lazy {
        lucideIcon(
            "Paperclip",
            stroke(
                "m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0",
                "8.485 8.485l8.379-8.551",
            ),
        )
    }

    /** Lucide `pen`. */
    val Pen: ImageVector by lazy {
        lucideIcon(
            "Pen",
            stroke(
                "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622",
                "l4.353-1.32a2 2 0 0 0 .83-.497z",
            ),
        )
    }

    /** Lucide `pen-line`. */
    val PenLine: ImageVector by lazy {
        lucideIcon(
            "PenLine",
            stroke("M13 21h8"),
            stroke(
                "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622",
                "l4.353-1.32a2 2 0 0 0 .83-.497z",
            ),
        )
    }

    /** Lucide `pencil`. */
    val Pencil: ImageVector by lazy {
        lucideIcon(
            "Pencil",
            stroke(
                "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622",
                "l4.353-1.32a2 2 0 0 0 .83-.497z",
            ),
            stroke("m15 5 4 4"),
        )
    }

    /** Lucide `plus`. */
    val Plus: ImageVector by lazy {
        lucideIcon(
            "Plus",
            stroke("M5 12h14"),
            stroke("M12 5v14"),
        )
    }

    /** Lucide `quote`. */
    val Quote: ImageVector by lazy {
        lucideIcon(
            "Quote",
            stroke(
                "M16 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6",
                "0 0 0 6-6V5a2 2 0 0 0-2-2z",
            ),
            stroke(
                "M5 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6 0",
                "0 0 6-6V5a2 2 0 0 0-2-2z",
            ),
        )
    }

    /** Lucide `redo-2`. */
    val Redo2: ImageVector by lazy {
        lucideIcon(
            "Redo2",
            stroke("m15 14 5-5-5-5"),
            stroke("M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13"),
        )
    }

    /** Lucide `rotate-ccw`. */
    val RotateCcw: ImageVector by lazy {
        lucideIcon(
            "RotateCcw",
            stroke("M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"),
            stroke("M3 3v5h5"),
        )
    }

    /** Lucide `ruler`. */
    val Ruler: ImageVector by lazy {
        lucideIcon(
            "Ruler",
            stroke(
                "M21.3 15.3a2.4 2.4 0 0 1 0 3.4l-2.6 2.6a2.4 2.4 0 0 1-3.4 0L2.7 8.7a2.41 2.41 0 0 1 0-3.4l2.6-2.6",
                "a2.41 2.41 0 0 1 3.4 0Z",
            ),
            stroke("m14.5 12.5 2-2"),
            stroke("m11.5 9.5 2-2"),
            stroke("m8.5 6.5 2-2"),
            stroke("m17.5 15.5 2-2"),
        )
    }

    /** Lucide `search`. */
    val Search: ImageVector by lazy {
        lucideIcon(
            "Search",
            stroke("m21 21-4.34-4.34"),
            stroke("M3 11A8 8 0 1 0 19 11A8 8 0 1 0 3 11Z"),
        )
    }

    /** Lucide `settings`. */
    val Settings: ImageVector by lazy {
        lucideIcon(
            "Settings",
            stroke(
                "M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34",
                "2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0",
                "2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35",
                "6.051a2.34 2.34 0 0 0 3.319-1.915",
            ),
            stroke("M9 12A3 3 0 1 0 15 12A3 3 0 1 0 9 12Z"),
        )
    }

    /** Lucide `shapes`. */
    val Shapes: ImageVector by lazy {
        lucideIcon(
            "Shapes",
            stroke("M8.3 10a.7.7 0 0 1-.626-1.079L11.4 3a.7.7 0 0 1 1.198-.043L16.3 8.9a.7.7 0 0 1-.572 1.1Z"),
            stroke("M4 14H9A1 1 0 0 1 10 15V20A1 1 0 0 1 9 21H4A1 1 0 0 1 3 20V15A1 1 0 0 1 4 14Z"),
            stroke("M14 17.5A3.5 3.5 0 1 0 21 17.5A3.5 3.5 0 1 0 14 17.5Z"),
        )
    }

    /** Lucide `share-2`. */
    val Share2: ImageVector by lazy {
        lucideIcon(
            "Share2",
            stroke("M15 5A3 3 0 1 0 21 5A3 3 0 1 0 15 5Z"),
            stroke("M3 12A3 3 0 1 0 9 12A3 3 0 1 0 3 12Z"),
            stroke("M15 19A3 3 0 1 0 21 19A3 3 0 1 0 15 19Z"),
            stroke("M8.59 13.51L15.42 17.49"),
            stroke("M15.41 6.51L8.59 10.49"),
        )
    }

    /** Lucide `sigma`. */
    val Sigma: ImageVector by lazy {
        lucideIcon(
            "Sigma",
            stroke(
                "M18 7V5a1 1 0 0 0-1-1H6.5a.5.5 0 0 0-.4.8l4.5 6a2 2 0 0 1 0 2.4l-4.5 6a.5.5 0 0 0 .4.8H17a1 1 0 0 0",
                "1-1v-2",
            ),
        )
    }

    /** Lucide `sliders-horizontal`. */
    val SlidersHorizontal: ImageVector by lazy {
        lucideIcon(
            "SlidersHorizontal",
            stroke("M10 5H3"),
            stroke("M12 19H3"),
            stroke("M14 3v4"),
            stroke("M16 17v4"),
            stroke("M21 12h-9"),
            stroke("M21 19h-5"),
            stroke("M21 5h-7"),
            stroke("M8 10v4"),
            stroke("M8 12H3"),
        )
    }

    /** Lucide `square`. */
    val Square: ImageVector by lazy {
        lucideIcon(
            "Square",
            stroke("M5 3H19A2 2 0 0 1 21 5V19A2 2 0 0 1 19 21H5A2 2 0 0 1 3 19V5A2 2 0 0 1 5 3Z"),
        )
    }

    /** Lucide `star`. */
    val Star: ImageVector by lazy {
        lucideIcon(
            "Star",
            stroke(
                "M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1",
                ".294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122",
                "2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16",
                "9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z",
            ),
        )
    }

    /** Lucide `sticky-note`. */
    val StickyNote: ImageVector by lazy {
        lucideIcon(
            "StickyNote",
            stroke(
                "M21 9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2",
                "2 0 0 0 2-2z",
            ),
            stroke("M15 3v5a1 1 0 0 0 1 1h5"),
        )
    }

    /** Lucide `strikethrough`. */
    val Strikethrough: ImageVector by lazy {
        lucideIcon(
            "Strikethrough",
            stroke("M16 4H9a3 3 0 0 0-2.83 4"),
            stroke("M14 12a4 4 0 0 1 0 8H6"),
            stroke("M4 12L20 12"),
        )
    }

    /** Lucide `table`. */
    val Table: ImageVector by lazy {
        lucideIcon(
            "Table",
            stroke("M12 3v18"),
            stroke("M5 3H19A2 2 0 0 1 21 5V19A2 2 0 0 1 19 21H5A2 2 0 0 1 3 19V5A2 2 0 0 1 5 3Z"),
            stroke("M3 9h18"),
            stroke("M3 15h18"),
        )
    }

    /** Lucide `tag`. */
    val Tag: ImageVector by lazy {
        lucideIcon(
            "Tag",
            stroke(
                "M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426",
                "0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z",
            ),
            filled("M7 7.5A0.5 0.5 0 1 0 8 7.5A0.5 0.5 0 1 0 7 7.5Z"),
        )
    }

    /** Lucide `trash`. */
    val Trash: ImageVector by lazy {
        lucideIcon(
            "Trash",
            stroke("M10 11v6"),
            stroke("M14 11v6"),
            stroke("M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"),
            stroke("M3 6h18"),
            stroke("M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"),
        )
    }

    /** Lucide `triangle`. */
    val Triangle: ImageVector by lazy {
        lucideIcon(
            "Triangle",
            stroke("M13.73 4a2 2 0 0 0-3.46 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"),
        )
    }

    /** Lucide `type`. */
    val Type: ImageVector by lazy {
        lucideIcon(
            "Type",
            stroke("M12 4v16"),
            stroke("M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2"),
            stroke("M9 20h6"),
        )
    }

    /** Lucide `undo-2`. */
    val Undo2: ImageVector by lazy {
        lucideIcon(
            "Undo2",
            stroke("M9 14 4 9l5-5"),
            stroke("M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11"),
        )
    }

    /** Lucide `x`. */
    val X: ImageVector by lazy {
        lucideIcon(
            "X",
            stroke("M18 6 6 18"),
            stroke("m6 6 12 12"),
        )
    }
}
